# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='keyword',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
