# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0003_auto_20161214_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='photo',
            field=models.ImageField(default=None, upload_to='images'),
        ),
    ]
