# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0004_image_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='keyword',
        ),
        migrations.AddField(
            model_name='image',
            name='keyword1',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='image',
            name='keyword2',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='image',
            name='keyword3',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
