# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0007_auto_20161228_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
    ]
